function mat = att2mat_321(phi,theta,psi)
  cpsi = cos(psi); spsi = sin(psi);
  cthe = cos(theta); sthe = sin(theta);
  cphi = cos(phi); sphi = sin(phi);
  C3 = [cpsi  spsi 0; ...
        -spsi cpsi 0; ...
         0     0   1];
  C2 = [cthe  0  -sthe; ...
          0   1     0 ; ...
        sthe  0   cthe];
  C1 = [1   0    0;   ...
        0  cphi sphi; ...
        0 -sphi cphi];  
  mat = C1 * C2 * C3;